// <auto-generated />
using APPssqlLite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APPssqlLite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231007115652_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("APPssqlLite.Model.Produit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float>("Prix")
                        .HasColumnType("REAL");

                    b.Property<string>("Titre")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
